CC = cc
RM = rm -f
CFLAGS = -Wall -Wextra -Werror -g
NAME = libft.a
SRC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c \
ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c \
ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_split.c ft_putchar_fd.c \
ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c get_next_line/get_next_line.c get_next_line/get_next_line_utils.c
BONUS_SRC = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c
OBJ = $(SRC:.c=.o)
BONUS_OBJ = $(BONUS_SRC:.c=.o)
PRINTF = ft_printf_fd.a
PRINTF_DIR = printf_fd

all: $(NAME)

# Need to link both the objects and the printf objects to the libft.a archive
$(NAME): $(PRINTF) $(OBJ)
	ar rcs $(NAME) $(OBJ)
	ar rcs $(NAME) $(PRINTF_DIR)/*.o

$(PRINTF):
	$(MAKE) -C $(PRINTF_DIR)

main: all
	$(CC) $(FLAGS) -L. $(NAME)

clean:
	rm -rf $(OBJ) $(BONUS_OBJ)
	rm -rf *.o
	$(MAKE) -C $(PRINTF_DIR) clean

fclean: clean
	rm -f $(NAME) a.out
	$(MAKE) -C $(PRINTF_DIR) fclean

re: fclean all

bonus: $(OBJ) $(BONUS_OBJ)
	ar rcs $(NAME) $(OBJ) $(BONUS_OBJ)

.PHONY:			all clean fclean re bonus
